service: backend_technical_test

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  # region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV}
    PORT: ${env:PORT}

plugins:
  - serverless-offline
  - serverless-plugin-typescript

functions:
  getSchedules:
    handler: src/modules/schedules/controller/agendaController.buscarAgendas
    events:
      - http:
          path: agendas
          method: get
          cors: true

  createAppointment:
    handler: src/modules/appointment/controller/agendamentoController.marcarAgendamento
    events:
      - http:
          path: agendamento
          method: post
          cors: true

custom:
  serverless-offline:
    port: 3000
    host: localhost
    httpPort: 3000
